version: 2.1

orbs:
    python: circleci/python@0.2.1

jobs:
    build:
        executor: python/default
        steps:
            - checkout
            - python/load-cache
            - python/install-deps
            - python/save-cache
    deploy:
        docker:
            - image: google/cloud-sdk
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Setup gcloud env
                  command: |
                      echo $MongoDB_Connection_String > apiKey.json
                      echo $GCP_KEY > gcloud-service-key.json
                      gcloud auth activate-service-account --key-file=gcloud-service-key.json
                      gcloud --quiet config set project ${GCP_PROJECT_ID}
                      gcloud --quiet config set compute/zone ${GCP_REGION}
            - run:
                  name: Deploy to App Engine
                  command: gcloud app deploy

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
