version: 2.1

orbs:
    python: circleci/python@0.2.1
    slack: circleci/slack@3.4.2

jobs:
    build:
        executor: python/default
        steps:
            - slack/approval-notification:
                  message: 新版本 Reco Flask 後端伺服器即將開始更新
                  webhook: https://hooks.slack.com/services/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
            - checkout
            - python/load-cache
            - python/install-deps
            - python/save-cache
            - run:
                  name: Install ApiKey file
                  command: echo $MongoDB_Connection_String > apiKey.json
            - persist_to_workspace:
                  root: .
                  paths:
                      - apiKey.json
                      - requirements.txt
                      - checksession.py
                      - date.py
                      - db.py
                      - main.py
                      - app.yaml
            - slack/approval-notification:
                  message: 新版本 Reco Flask 後端伺服器完成 Build 工作階段！
                  webhook: https://hooks.slack.com/services/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
    deploy:
        docker:
            - image: google/cloud-sdk
        steps:
            - attach_workspace:
                  at: .
            - slack/approval-notification:
                  message: 新版本 Reco Flask 後端伺服器開始部署
                  webhook: https://hooks.slack.com/services/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
            - run:
                  name: Setup gcloud env
                  command: |
                      echo $GCP_KEY > gcloud-service-key.json
                      gcloud auth activate-service-account --key-file=gcloud-service-key.json
                      gcloud --quiet config set project ${GCP_PROJECT_ID}
                      gcloud --quiet config set compute/zone ${GCP_REGION}
            - run:
                  name: Deploy to App Engine
                  command: gcloud app deploy
                  no_output_timeout: 30m
            - slack/status:
                  fail_only: false
                  mentions: "U0138PGJF4G"
                  only_for_branches: master
                  webhook: https://hooks.slack.com/services/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

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
